export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",

  REMOVE_ITEM_FROM_CART_REQUEST: "REMOVE_ITEM_FROM_CART_REQUEST",
  REMOVE_ITEM_FROM_CART_SUCCESS: "REMOVE_ITEM_FROM_CART_SUCCESS",
  REMOVE_ITEM_FROM_CART_FAILURE: "REMOVE_ITEM_FROM_CART_FAILURE",

  FETCH_CART_REQUEST: "FETCH_CART_REQUEST",
  FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
  FETCH_CART_FAILURE: "FETCH_CART_FAILURE",

  UPDATE_CART_REQUEST: "UPDATE_CART_REQUEST",
  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  UPDATE_CART_FAILURE: "UPDATE_CART_FAILURE",

  INCREMENT_ITEM_QUANTITY: "INCREMENT_ITEM_QUANTITY",
  DECREMENT_ITEM_QUANTITY: "DECREMENT_ITEM_QUANTITY",
  UPDATE_ACTIVE_CART_ITEM: "UPDATE_ACTIVE_CART_ITEM",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
